name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    environment: test

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3310:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    env:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      USERNAME1: ${{ secrets.USERNAME1 }}
      USERNAME2: ${{ secrets.USERNAME2 }}
      USERNAME3: ${{ secrets.USERNAME3 }}
      USERNAME4: ${{ secrets.USERNAME4 }}
      PASSWORD1: ${{ secrets.PASSWORD1 }}
      PASSWORD2: ${{ secrets.PASSWORD2 }}
      PASSWORD3: ${{ secrets.PASSWORD3 }}
      PASSWORD4: ${{ secrets.PASSWORD4 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install root deps
        run: npm install

      - name: Install client deps
        run: cd client && npm install

      - name: Install server deps
        run: cd server && npm install

        #  waiting for MySQL
      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do 
            echo "Waiting for MySQL..."
            sleep 5 
          done

        # migrations/seed
      - name: Run migrations/seed
        run: cd server && npm run migrate && npm run seed

      # Start Express backend
      - name: Start app
        run: npm start

      # Wait until Vite is ready
      - name: Wait for frontend
        run: npx wait-on http://localhost:3001

      # Run Cypress tests
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: "http://localhost:3001"
          config-file: cypress.config.js

      # Upload artifacts if tests fail
      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
