name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    environment: test

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval \"db.adminCommand({ ping: 1 })\""
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      USERNAME1: ${{ secrets.USERNAME1 }}
      USERNAME2: ${{ secrets.USERNAME2 }}
      USERNAME3: ${{ secrets.USERNAME3 }}
      USERNAME4: ${{ secrets.USERNAME4 }}
      PASSWORD1: ${{ secrets.PASSWORD1 }}
      PASSWORD2: ${{ secrets.PASSWORD2 }}
      PASSWORD3: ${{ secrets.PASSWORD3 }}
      PASSWORD4: ${{ secrets.PASSWORD4 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install root deps
        run: npm install

      - name: Install client deps
        run: cd client && npm install

      - name: Install server deps
        run: cd server && npm install

      - name: Start app
        run: npm start &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3001

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          wait-on: "http://localhost:3001"
          config-file: cypress.config.js

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
